################################################################################
# WARNING: This MongoDB deployment is not suitable for production as the data is
# not persistently stored and will go away every time the Pod restarts. Consider
# using a Helm chart that provisions a StatefulSet instead of Deployment.
################################################################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aurora-mongodb
  labels:
    app: aurora
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurora
      tier: db
  template:
    metadata:
      labels:
        app: aurora
        tier: db
    spec:
      containers:
        - name: mongo
          image: mongo:4
          ports:
            - containerPort: 27017
